### ISSUE TITLE
Django 1.8+ support

### ISSUE THREAD

**Issue by buchuki** [django-postgres-metrics/django-postgres-metrics#13]
{% resetcycle %} tag is introduced in Django 1.11 and is causing the templates to fail:

```
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 48: 'resetcycle', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
```

**Comment by MarkusH** [comment]
I'm going a bit further with this and say we should add Django 1.8+ support. PR incoming, based on yours

**Comment by MarkusH** [comment]
So, turns out supporting Django 1.8 is rather hard or cumbersome here because of these issues:

- Template inheritence works differently
- the `simple_tag` for template tags can be used as an assignment tag only on Django 1.9

Since 1.9 and 1.10 aren't supported much longer I propose to just not support Django<1.11.

**Comment by MarkusH** [comment]
won't fix
